name: Auto Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly set write permission to repository contents
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history so we can push properly
        
      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Generate random message and update file
        run: |
          # Get current date and time
          current_time=$(date "+%Y-%m-%d %H:%M:%S")
          
          # Fetch a random commit message from whatthecommit.com
          random_commit_message=$(curl -s https://whatthecommit.com/index.txt)
          
          # Append to the commit-log.txt file instead of overwriting
          echo "$current_time - $random_commit_message" >> commit-log.txt
          
      - name: Commit and push changes
        run: |
          git add commit-log.txt
          git commit -m "$(curl -s https://whatthecommit.com/index.txt)"
          git push
